# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1)),
                ('iso', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
