# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['iso'], 'verbose_name_plural': 'currencies'},
        ),
    ]
