# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160926_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Currency'),
        ),
    ]
