# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organisation_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humanitarian_or_development', models.CharField(choices=[('H', 'Humanitarian'), ('D', 'Development')], default='H', max_length=1)),
                ('loan_or_grant', models.CharField(choices=[('L', 'Loan'), ('G', 'Grant')], default='G', max_length=1)),
                ('concessional', models.BooleanField(default=True)),
                ('pledge_or_disbursement', models.CharField(choices=[('P', 'Pledge'), ('D', 'Disbursement')], default='P', max_length=1)),
                ('recipient', models.CharField(choices=[('S', 'Syria'), ('J', 'Jordan'), ('L', 'Lebanon'), ('I', 'Iraq'), ('E', 'Egypt'), ('T', 'Turkey'), ('R', 'Region'), ('N', 'Not defined')], default='N', max_length=1)),
                ('year', models.IntegerField(blank=True, choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='If no ', max_digits=99, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Currency')),
            ],
        ),
        migrations.AlterField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organisation'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sector',
            field=models.ManyToManyField(blank=True, related_name='sectors', related_query_name='sector', to='core.Sector'),
        ),
    ]
