# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160926_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='default_currency',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If no amount was pledged/disbursed, record amount as zero. Otherwise leave field missing for unknown amount.', max_digits=99, null=True),
        ),
    ]
