# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161005_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='humanitarian_or_development',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='outside_london_conference',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pledge_or_disbursement',
            field=models.CharField(choices=[('P', 'Pledged'), ('M', 'Committed'), ('C', 'Contracted'), ('D', 'Disbursed')], default='P', max_length=1),
        ),
    ]
