# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20161005_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
