# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_transaction_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='comments',
            new_name='comment',
        ),
    ]
