# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20161006_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='default_currency',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.Currency'),
            preserve_default=False,
        ),
    ]
