# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_organisation_default_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='default_currency',
        ),
    ]
