# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_spreadsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=300)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
                ('spreadsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Spreadsheet')),
            ],
        ),
    ]
