# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
