# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20161006_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='grant_making',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='loan_making',
            field=models.BooleanField(default=True),
        ),
    ]
