# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20161007_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='government',
            field=models.BooleanField(default=True),
        ),
    ]
