# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_organisation_government'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sector',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
