# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20161007_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='channel_of_delivery',
            field=models.CharField(blank=True, choices=[('U', 'UN agencies'), ('N', 'NGOs'), ('R', 'RCRC'), ('G', 'Government institutions'), ('P', 'Private sector'), ('O', 'Other channel of delivery')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='concessional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='loan_or_grant',
            field=models.CharField(blank=True, choices=[('L', 'Loan'), ('G', 'Grant')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='pledge_or_disbursement',
            field=models.CharField(blank=True, choices=[('P', 'Pledged'), ('M', 'Committed'), ('C', 'Contracted'), ('D', 'Disbursed')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='recipient',
            field=models.CharField(choices=[('S', 'Syria'), ('J', 'Jordan'), ('L', 'Lebanon'), ('I', 'Iraq'), ('E', 'Egypt'), ('T', 'Turkey'), ('R', 'Region'), ('N', 'Not defined')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='entry',
            name='refugee_facility_for_turkey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sector'),
        ),
    ]
