# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20161007_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='coordinates',
            field=models.CharField(editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='entry',
            name='spreadsheet',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Spreadsheet'),
        ),
    ]
