# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20161010_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='recipient',
            field=models.CharField(choices=[('S', 'Syria'), ('J', 'Jordan'), ('L', 'Lebanon'), ('T', 'Turkey'), ('I', 'Iraq'), ('E', 'Egypt'), ('R', 'Region'), ('N', 'Not defined')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, '2017-2020')]),
        ),
    ]
