# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20161017_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='refugee_facility_for_turkey',
            field=models.CharField(blank=True, choices=[('L', 'Contributions relating to London Conference pledges'), ('N', 'Contributions beyond London Conference pledges')], max_length=1, null=True),
        ),
    ]
