# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20161017_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='sectors', related_query_name='sector', to='core.Sector'),
        ),
    ]
