# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20161107_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='channel_of_delivery',
            field=models.CharField(blank=True, choices=[('U', 'UN agencies'), ('N', 'NGOs'), ('R', 'RCRC'), ('G', 'Partner country government'), ('P', 'Private sector'), ('O', 'Other channel of delivery (please detail in the comments box)')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, '2017-2020'), (1, 2017), (2, '2018-2020')]),
        ),
    ]
